In [1]:
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 4.0 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [9]:
import pandas as pd 
import numpy as np 
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv("RAW DATASET.csv")
df.head()

,Index_Place,City,Name_SMEs,General_Category,Specialty,Price_Range,Rating,Goods
0,J_01,Jakarta,Jari Indahati,Craft,Tas Rotan Batik,>50.000,4.5,Souvenir
1,J_02,Jakarta,AiU Craft,Craft,Tas Kanvas,>50.000,4.9,Souvenir
2,J_03,Jakarta,Noei Craft,Craft,Souvenir Goni,25.000-50.000,4.8,Souvenir
3,J_04,Jakarta,Al zheefa Lombok Craft,Craft,Tas Anyaman,>50.000,5.0,Souvenir
4,J_05,Jakarta,Betawi Online Gallery,Craft,"Miniatur Monas, Miniatur Ondel-Ondel",25.000-50.000,4.6,Souvenir

In [4]:
df1_copy = df.copy()
df1_copy

,Index_Place,City,Name_SMEs,General_Category,Specialty,Price_Range,Rating,Goods
0,J_01,Jakarta,Jari Indahati,Craft,Tas Rotan Batik,>50.000,4.5,Souvenir
1,J_02,Jakarta,AiU Craft,Craft,Tas Kanvas,>50.000,4.9,Souvenir
2,J_03,Jakarta,Noei Craft,Craft,Souvenir Goni,25.000-50.000,4.8,Souvenir
3,J_04,Jakarta,Al zheefa Lombok Craft,Craft,Tas Anyaman,>50.000,5.0,Souvenir
4,J_05,Jakarta,Betawi Online Gallery,Craft,"Miniatur Monas, Miniatur Ondel-Ondel",25.000-50.000,4.6,Souvenir
...,...,...,...,...,...,...,...,...
315,BD_51,Bandung,Garasi Craft,Craft,Gantungan kunci,<25.000,5.0,Souvenir
316,BD_52,Bandung,The Dreamer Craft,Craft,Gantungan kunci kulit,>50.000,5.0,Souvenir
317,BD_53,Bandung,Rona Ratu Fashion,Craft,Anting bunga,<25.000,4.8,Souvenir
318,BD_54,Bandung,Diah CraftShop,Craft,Tas Rajut,25.000-50.000,4.9,Souvenir
319,BD_55,Bandung,Krizatnik.Craft,Craft,Tas Rajut,25.000-50.000,4.3,Souvenir

In [5]:
stm = StemmerFactory().create_stemmer()
stop = StopWordRemoverFactory().create_stop_word_remover()

In [6]:
def cleaning(word):
    word = word.lower()
    word = stm.stem(word)
    word = stop.remove(word)
    return word

In [7]:
df1_copy['city_category'] = df1_copy[['City','General_Category']].agg(' '.join,axis=1)
df1_copy

,Index_Place,City,Name_SMEs,General_Category,Specialty,Price_Range,Rating,Goods,city_category
0,J_01,Jakarta,Jari Indahati,Craft,Tas Rotan Batik,>50.000,4.5,Souvenir,Jakarta Craft
1,J_02,Jakarta,AiU Craft,Craft,Tas Kanvas,>50.000,4.9,Souvenir,Jakarta Craft
2,J_03,Jakarta,Noei Craft,Craft,Souvenir Goni,25.000-50.000,4.8,Souvenir,Jakarta Craft
3,J_04,Jakarta,Al zheefa Lombok Craft,Craft,Tas Anyaman,>50.000,5.0,Souvenir,Jakarta Craft
4,J_05,Jakarta,Betawi Online Gallery,Craft,"Miniatur Monas, Miniatur Ondel-Ondel",25.000-50.000,4.6,Souvenir,Jakarta Craft
...,...,...,...,...,...,...,...,...,...
315,BD_51,Bandung,Garasi Craft,Craft,Gantungan kunci,<25.000,5.0,Souvenir,Bandung Craft
316,BD_52,Bandung,The Dreamer Craft,Craft,Gantungan kunci kulit,>50.000,5.0,Souvenir,Bandung Craft
317,BD_53,Bandung,Rona Ratu Fashion,Craft,Anting bunga,<25.000,4.8,Souvenir,Bandung Craft
318,BD_54,Bandung,Diah CraftShop,Craft,Tas Rajut,25.000-50.000,4.9,Souvenir,Bandung Craft
319,BD_55,Bandung,Krizatnik.Craft,Craft,Tas Rajut,25.000-50.000,4.3,Souvenir,Bandung Craft

In [8]:
df1_copy.city_category = df1_copy.city_category.apply(cleaning)
df1_copy

,Index_Place,City,Name_SMEs,General_Category,Specialty,Price_Range,Rating,Goods,city_category
0,J_01,Jakarta,Jari Indahati,Craft,Tas Rotan Batik,>50.000,4.5,Souvenir,jakarta craft
1,J_02,Jakarta,AiU Craft,Craft,Tas Kanvas,>50.000,4.9,Souvenir,jakarta craft
2,J_03,Jakarta,Noei Craft,Craft,Souvenir Goni,25.000-50.000,4.8,Souvenir,jakarta craft
3,J_04,Jakarta,Al zheefa Lombok Craft,Craft,Tas Anyaman,>50.000,5.0,Souvenir,jakarta craft
4,J_05,Jakarta,Betawi Online Gallery,Craft,"Miniatur Monas, Miniatur Ondel-Ondel",25.000-50.000,4.6,Souvenir,jakarta craft
...,...,...,...,...,...,...,...,...,...
315,BD_51,Bandung,Garasi Craft,Craft,Gantungan kunci,<25.000,5.0,Souvenir,bandung craft
316,BD_52,Bandung,The Dreamer Craft,Craft,Gantungan kunci kulit,>50.000,5.0,Souvenir,bandung craft
317,BD_53,Bandung,Rona Ratu Fashion,Craft,Anting bunga,<25.000,4.8,Souvenir,bandung craft
318,BD_54,Bandung,Diah CraftShop,Craft,Tas Rajut,25.000-50.000,4.9,Souvenir,bandung craft
319,BD_55,Bandung,Krizatnik.Craft,Craft,Tas Rajut,25.000-50.000,4.3,Souvenir,bandung craft

In [12]:
cv = CountVectorizer()
cv.fit(df1_copy['city_category'])
print("Features Name: ", list(cv.vocabulary_.keys()))

Features Name:  ['jakarta', 'craft', 'munchies', 'fashion', 'yogyakarta', 'surakarta', 'bal', 'bandung']

In [13]:
cvt_mat= cv.transform(df1_copy['city_category']) 
cvt_mat.shape

(320, 8)

In [14]:
cvt_mat.todense()

matrix([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 1, 1, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0]])

In [15]:
similarity = cosine_similarity(cvt_mat)
similarity

array([[1. , 1. , 1. , ..., 0.5, 0.5, 0.5],
       [1. , 1. , 1. , ..., 0.5, 0.5, 0.5],
       [1. , 1. , 1. , ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 1. , 1. , 1. ],
       [0.5, 0.5, 0.5, ..., 1. , 1. , 1. ],
       [0.5, 0.5, 0.5, ..., 1. , 1. , 1. ]])

In [16]:
sim_df = pd.DataFrame(similarity,index=df1_copy['Name_SMEs'],columns=df1_copy['Name_SMEs'])
sim_df

Name_SMEs,Jari Indahati,AiU Craft,Noei Craft,Al zheefa Lombok Craft,Betawi Online Gallery,Reyhan Souvenir,Flanelly Businesz,Native Borneo,Poi Poi,J-Craft,...,Rustic Hut Craft,Bale Angklung Bandung,Giri Harja Galery Art Wayang Golek,Wayang Golek Bapak Ramdan,Bandung Rustik Market,Garasi Craft,The Dreamer Craft,Rona Ratu Fashion,Diah CraftShop,Krizatnik.Craft
Name_SMEs,,,,,,,,,,,,,,,,,,,,,
Jari Indahati,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
AiU Craft,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
Noei Craft,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
Al zheefa Lombok Craft,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
Betawi Online Gallery,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Garasi Craft,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
The Dreamer Craft,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Rona Ratu Fashion,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Diah CraftShop,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Krizatnik.Craft,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [17]:
sim_df.to_csv("sim.csv", index=True)

In [18]:
sim = pd.read_csv("sim.csv").set_index("Name_SMEs")

In [19]:
sim

,Jari Indahati,AiU Craft,Noei Craft,Al zheefa Lombok Craft,Betawi Online Gallery,Reyhan Souvenir,Flanelly Businesz,Native Borneo,Poi Poi,J-Craft,...,Rustic Hut Craft,Bale Angklung Bandung,Giri Harja Galery Art Wayang Golek,Wayang Golek Bapak Ramdan,Bandung Rustik Market,Garasi Craft,The Dreamer Craft,Rona Ratu Fashion,Diah CraftShop,Krizatnik.Craft
Name_SMEs,,,,,,,,,,,,,,,,,,,,,
Jari Indahati,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
AiU Craft,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
Noei Craft,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
Al zheefa Lombok Craft,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
Betawi Online Gallery,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Garasi Craft,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
The Dreamer Craft,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Rona Ratu Fashion,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Diah CraftShop,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Krizatnik.Craft,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [20]:
def rec(place_name,similarity_data=sim,k=3):
    index = similarity_data.loc[:,place_name].to_numpy().argpartition(range(-1,-k,-1))
    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    closest = closest.drop(place_name,errors='ignore')
    return closest

In [21]:
rec("Bali Miho")

Index(['Bli Ketut Ukir', 'Kipas Bee Handycrafts', 'Dream Catcher Bali'], dtype='object')